<a href="https://colab.research.google.com/github/Ayush-Singh-as/Knowledge-Lab/blob/main/NumPy_Learning_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. NumPy Basics

An one-dimensional NumPy Array

In [2]:
a = [1, 2, 3]
np.array(a)

array([1, 2, 3])

A 2d NumPy Array

In [3]:
lst = [[1, 2, 3],
       [4, 5, 6]]
array2d = np.array(lst)
array2d

array([[1, 2, 3],
       [4, 5, 6]])

Lets check the data type of the array -

In [5]:
array2d.dtype

dtype('int64')

How to define an array of specific data type like int32?

In [9]:
int32Array = np.array(lst, dtype=np.int32)
int32Array

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

We can also downcast or recast array's data type using the astype method like -

In [11]:
int32array = array2d.astype(np.int32)
int32array

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

To return the number of elements in an array, we can use the size attribute, as shown below:



In [12]:
array2d.size

6

And the number of dimensions of our array (Intuitively, you may think of dimensions as the rank of a tensor) can be obtained via the ndim attribute:

In [13]:
array2d.ndim

2

To return the number of elements along each array dimension (in 2d array it will be number of rows and columns) we can use the shape attribute as shown below:

In [14]:
array2d.shape

(2, 3)

# 2. NumPy Array Construction and Indexing