<a href="https://colab.research.google.com/github/Ayush-Singh-as/Knowledge-Lab/blob/main/NumPy_Learning_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. NumPy Basics

An one-dimensional NumPy Array

In [ ]:
a = [1, 2, 3]
np.array(a)

array([1, 2, 3])

A 2d NumPy Array

In [ ]:
lst = [[1, 2, 3],
       [4, 5, 6]]
array2d = np.array(lst)
array2d

array([[1, 2, 3],
       [4, 5, 6]])

Lets check the data type of the array -

In [ ]:
array2d.dtype

dtype('int64')

How to define an array of specific data type like int32?

In [ ]:
int32Array = np.array(lst, dtype=np.int32)
int32Array

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

We can also downcast or recast array's data type using the astype method like -

In [ ]:
int32array = array2d.astype(np.int32)
int32array

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

To return the number of elements in an array, we can use the size attribute, as shown below:



In [ ]:
array2d.size

6

And the number of dimensions of our array (Intuitively, you may think of dimensions as the rank of a tensor) can be obtained via the ndim attribute:

In [ ]:
array2d.ndim

2

To return the number of elements along each array dimension (in 2d array it will be number of rows and columns) we can use the shape attribute as shown below:

In [ ]:
array2d.shape

(2, 3)

# 2. NumPy Array Construction and Indexing

## Array Construction

Constructing an array containing ones or zeroes only:

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

We can use these functions to create arrays with arbitrary value:

In [ ]:
np.zeros((3, 3)) + 5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

We can also create an empty array which can act as a placeholder array:

In [ ]:
np.empty((3, 3))

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

Note: An empty array will contain whatever random values were already sitting in the memory.

NumPy also comes with functions to create identity matrices and diagonal matrices as ndarrays:

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Lastly, I want to mention two very useful functions for creating sequences of numbers within a specified range, namely, arange and linspace:

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

If we only provide a single function argument, the range object treats this number as the endpoint of the interval and starts at 0:

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In NumPy's arange function, a third argument can be provided to define the step (the default step size is 1):*italicized text*

In [ ]:
np.arange(1, 2, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

PS: NumPy's arange function is similar to python's range objects.

The linspace function is especially useful if we want to create a particular number of evenly spaced values in a specified half-open interval:

In [ ]:
np.linspace(1, 10, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(1, 10, num=17)

array([ 1.    ,  1.5625,  2.125 ,  2.6875,  3.25  ,  3.8125,  4.375 ,
        4.9375,  5.5   ,  6.0625,  6.625 ,  7.1875,  7.75  ,  8.3125,
        8.875 ,  9.4375, 10.    ])

In [ ]:
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Array Indexing

NumPy indexing and slicing works similar to Python lists, which we will demonstrate in the following code snippets:

In [ ]:
ary = np.array([1, 2, 3])
ary[1]

np.int64(1)

Indexing a NumPy array gives a NumPy number (like np.int64) instead of a normal Python number so it matches the array’s data type.

In [ ]:
ary[0:2] # Slicing

array([1, 2])

If we work with arrays that have more than one dimension or axis, we separate our indexing or slicing operations by commas as shown in the series of examples below:

In [ ]:
ary = np.array([[1, 2, 3],
                [4, 5, 6]])
ary[0, 2] # first row last column

np.int64(3)

In [ ]:
ary[1, 1] # second row second column

np.int64(5)

In [ ]:
ary[-1, -1] # last row last column

np.int64(6)

In [ ]:
ary[:, 0] # entire first column

array([1, 4])

In [ ]:
ary[:, :2] # first two columns

array([[1, 2],
       [4, 5]])

# 3. NumPy Array Math and Universal Functions

In the previous sections, you learned how to create NumPy arrays and how to access different elements in an array. It is about time that we introduce one of the core features of NumPy that makes working with ndarray so efficient and convenient: vectorization. While we typically use for-loops if we want to perform arithmetic operations on sequence-like objects, NumPy provides vectorized wrappers for performing element-wise operations implicitly via so-called ufuncs – “ufuncs” is short for universal functions.

Check out the [official documentation](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs) for a complete list of ufuncs available in NumPy.

The ufuncs for basic arithmetic operations are add, subtract, divide, multiply, power, and exp (exponential). However, NumPy uses operator overloading so that we can use mathematical operators (+, -, /, *, and **) directly:

In [4]:
lst = [[1, 2, 3],
        [4, 5, 6]]
ary = np.array(lst)
np.add(ary, 1)

array([[2, 3, 4],
       [5, 6, 7]])

In [5]:
ary + 1

array([[2, 3, 4],
       [5, 6, 7]])

In addition, NumPy implements several useful unary ufuncs, such as log (natural logarithm), log10 (base-10 logarithm), and sqrt (square root):

In [6]:
np.log(ary)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

Often, we want to compute the sum or product of array element along a given axis. For this purpose, we can use a ufunc’s reduce operation. By default, reduce applies an operation along the first axis (axis=0):

In [7]:
np.add.reduce(ary)

array([5, 7, 9])

In [8]:
np.add.reduce(ary, axis=1)

array([ 6, 15])

NumPy also provides specific functions such as sum and product:

In [10]:
ary.sum(axis=0)

array([5, 7, 9])

Note: Both product and sum function compute the product and sum of the entire array if we do not define an axis:

In [11]:
ary.sum()

np.int64(21)

Other useful unary ufuncs are:

* np.mean (computes arithmetic mean or average)
* np.std (computes the standard deviation)
* np.var (computes variance)
* np.sort (sorts an array)
* np.argsort (returns indices that would sort an array)
* np.min (returns the minimum value of an array)
* np.max (returns the maximum value of an array)
* np.argmin (returns the index of the minimum value)
* np.argmax (returns the index of the maximum value)
* np.array_equal (checks if two arrays have the same shape and elements)

# 4. NumPy Broadcasting